/* generated by rust_qt_binding_generator */
#![allow(unknown_lints)]
#![allow(mutex_atomic, needless_pass_by_value)]
use libc::{c_int, c_void, uint8_t, uint16_t};
use std::slice;

use std::sync::{Arc, Mutex};
use std::ptr::null;

use implementation::*;


#[repr(C)]
pub struct COption<T> {
    data: T,
    some: bool,
}

impl<T> From<Option<T>> for COption<T>
where
    T: Default,
{
    fn from(t: Option<T>) -> COption<T> {
        if let Some(v) = t {
            COption {
                data: v,
                some: true,
            }
        } else {
            COption {
                data: T::default(),
                some: false,
            }
        }
    }
}


#[repr(C)]
pub struct QString {
    data: *const uint8_t,
    len: c_int,
}

#[repr(C)]
pub struct QStringIn {
    data: *const uint16_t,
    len: c_int,
}

impl QStringIn {
    fn convert(&self) -> String {
        let data = unsafe { slice::from_raw_parts(self.data, self.len as usize) };
        String::from_utf16_lossy(data)
    }
}

impl<'a> From<&'a str> for QString {
    fn from(string: &'a str) -> QString {
        QString {
            len: string.len() as c_int,
            data: string.as_ptr(),
        }
    }
}

impl<'a> From<&'a String> for QString {
    fn from(string: &'a String) -> QString {
        QString {
            len: string.len() as c_int,
            data: string.as_ptr(),
        }
    }
}


#[repr(C)]
pub enum SortOrder {
    Ascending = 0,
    Descending = 1,
}

#[repr(C)]
pub struct QModelIndex {
    row: c_int,
    internal_id: usize,
}

pub struct TasksQObject {}

#[derive(Clone)]
pub struct TasksEmitter {
    qobject: Arc<Mutex<*const TasksQObject>>,
    new_data_ready: fn(*const TasksQObject),
}

unsafe impl Send for TasksEmitter {}

impl TasksEmitter {
    fn clear(&self) {
        *self.qobject.lock().unwrap() = null();
    }
    pub fn new_data_ready(&self) {
        let ptr = *self.qobject.lock().unwrap();
        if !ptr.is_null() {
            (self.new_data_ready)(ptr);
        }
    }
}

pub struct TasksList {
    qobject: *const TasksQObject,
    data_changed: fn(*const TasksQObject, usize, usize),
    begin_reset_model: fn(*const TasksQObject),
    end_reset_model: fn(*const TasksQObject),
    begin_insert_rows: fn(*const TasksQObject, usize, usize),
    end_insert_rows: fn(*const TasksQObject),
    begin_remove_rows: fn(*const TasksQObject, usize, usize),
    end_remove_rows: fn(*const TasksQObject),
}

impl TasksList {
    pub fn data_changed(&self, first: usize, last: usize) {
        (self.data_changed)(self.qobject, first, last);
    }
    pub fn begin_reset_model(&self) {
        (self.begin_reset_model)(self.qobject);
    }
    pub fn end_reset_model(&self) {
        (self.end_reset_model)(self.qobject);
    }
    pub fn begin_insert_rows(&self, first: usize, last: usize) {
        (self.begin_insert_rows)(self.qobject, first, last);
    }
    pub fn end_insert_rows(&self) {
        (self.end_insert_rows)(self.qobject);
    }
    pub fn begin_remove_rows(&self, first: usize, last: usize) {
        (self.begin_remove_rows)(self.qobject, first, last);
    }
    pub fn end_remove_rows(&self) {
        (self.end_remove_rows)(self.qobject);
    }
}

pub trait TasksTrait {
    fn new(emit: TasksEmitter, model: TasksList) -> Self;
    fn emit(&self) -> &TasksEmitter;
    fn sweep(&mut self) -> bool;
    fn row_count(&self) -> usize;
    fn insert_rows(&mut self, row: usize, count: usize) -> bool { false }
    fn remove_rows(&mut self, row: usize, count: usize) -> bool { false }
    fn can_fetch_more(&self) -> bool {
        false
    }
    fn fetch_more(&mut self) {}
    fn sort(&mut self, u8, SortOrder) {}
    fn completed(&self, item: usize) -> bool;
    fn set_completed(&mut self, item: usize, bool) -> bool;
    fn title(&self, item: usize) -> &str;
    fn set_title(&mut self, item: usize, String) -> bool;
}

#[no_mangle]
pub extern "C" fn tasks_new(
    tasks: *mut TasksQObject,
    tasks_new_data_ready: fn(*const TasksQObject),
    tasks_data_changed: fn(*const TasksQObject, usize, usize),
    tasks_begin_reset_model: fn(*const TasksQObject),
    tasks_end_reset_model: fn(*const TasksQObject),
    tasks_begin_insert_rows: fn(*const TasksQObject, usize, usize),
    tasks_end_insert_rows: fn(*const TasksQObject),
    tasks_begin_remove_rows: fn(*const TasksQObject, usize, usize),
    tasks_end_remove_rows: fn(*const TasksQObject),
) -> *mut Tasks {
    let tasks_emit = TasksEmitter {
        qobject: Arc::new(Mutex::new(tasks)),
        new_data_ready: tasks_new_data_ready,
    };
    let model = TasksList {
        qobject: tasks,
        data_changed: tasks_data_changed,
        begin_reset_model: tasks_begin_reset_model,
        end_reset_model: tasks_end_reset_model,
        begin_insert_rows: tasks_begin_insert_rows,
        end_insert_rows: tasks_end_insert_rows,
        begin_remove_rows: tasks_begin_remove_rows,
        end_remove_rows: tasks_end_remove_rows,
    };
    let d_tasks = Tasks::new(tasks_emit, model);
    Box::into_raw(Box::new(d_tasks))
}

#[no_mangle]
pub unsafe extern "C" fn tasks_free(ptr: *mut Tasks) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn tasks_sweep(ptr: *mut Tasks) -> bool {
    (&mut *ptr).sweep()
}

#[no_mangle]
pub unsafe extern "C" fn tasks_row_count(ptr: *const Tasks) -> c_int {
    (&*ptr).row_count() as c_int
}
#[no_mangle]
pub unsafe extern "C" fn tasks_insert_rows(ptr: *mut Tasks, row: c_int, count: c_int) -> bool {
    (&mut *ptr).insert_rows(row as usize, count as usize)
}
#[no_mangle]
pub unsafe extern "C" fn tasks_remove_rows(ptr: *mut Tasks, row: c_int, count: c_int) -> bool {
    (&mut *ptr).remove_rows(row as usize, count as usize)
}
#[no_mangle]
pub unsafe extern "C" fn tasks_can_fetch_more(ptr: *const Tasks) -> bool {
    (&*ptr).can_fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn tasks_fetch_more(ptr: *mut Tasks) {
    (&mut *ptr).fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn tasks_sort(
    ptr: *mut Tasks,
    column: u8,
    order: SortOrder,
) {
    (&mut *ptr).sort(column, order)
}

#[no_mangle]
pub unsafe extern "C" fn tasks_data_completed(ptr: *const Tasks, row: c_int) -> bool {
    (&*ptr).completed(row as usize).into()
}

#[no_mangle]
pub unsafe extern "C" fn tasks_set_data_completed(
    ptr: *mut Tasks, row: c_int,
    v: bool,
) -> bool {
    (&mut *ptr).set_completed(row as usize, v)
}

#[no_mangle]
pub unsafe extern "C" fn tasks_data_title(
    ptr: *const Tasks, row: c_int,
    d: *mut c_void,
    set: fn(*mut c_void, QString),
) {
    let data = (&*ptr).title(row as usize);
    set(d, (data).into());
}

#[no_mangle]
pub unsafe extern "C" fn tasks_set_data_title(
    ptr: *mut Tasks, row: c_int,
    v: QStringIn,
) -> bool {
    (&mut *ptr).set_title(row as usize, v.convert())
}
